### ISSUE TITLE
no matches for kind "TriggerTemplate" in version "tekton.dev/v1alpha1"

### ISSUE THREAD

**Issue by loafyloaf** [ncskier/catapp#4]
https://github.com/ncskier/catapp/blob/d28e5d008b4f90661dedcec95943da3179a8288c/tekton/build-and-deploy-openshift-triggers.yaml#L1

I had to change this and a couple of other lines to 'triggers.tekton.dev' to get them to apply. I manually installed pipelines/triggers in my cluster, though (as opposed to using the operator), so maybe that's why...

**Comment by ncskier** [comment]
Thanks for the feedback @loafyloaf. I just updated the project to work with the Tekton beta & Tekton Triggers v0.4.0 👍 

I also created an [`alpha`](https://github.com/ncskier/catapp/tree/alpha) branch for people who are still using alpha versions of Tekton (that branch currently works with the OpenShift Pipelines Operator versions 0.10.8 and 0.10.7).
